disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
line_length: 250
  # they can set both implicitly with an array
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
